[build]
  command = "cd backend && npm install"
  publish = "frontend"
  functions = "backend"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/server/:splat"
  status = 200
  force = true
